version: "3.8"

services:
  frontend:
    build: frontend-react
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend
      - backend:backend

  backend:
    container_name: backend
    build: backend-node
    ports:
      - "3000:3000"
    depends_on:
      - db
      - test_db
    links:
      - db
      - db:database
      - test_db
      - test_db:test_db

  db:
    build: database/db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  test_db:
    build: database/test_db
    restart: always
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  pgdata:
  pgdata_test:
